use_frameworks!

target 'lojinha_StoreFront_Example' do
  pod 'lojinha_StoreFront', :path => '../'

  #Modules
  pod 'lojinha_Common', :path => '../../lojinha_Common'

  target 'lojinha_StoreFront_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
