# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lojinha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManager'

  target 'lojinhaTests' do
    inherit! :search_paths
    pod 'Nimble', '8.0.2'
    pod 'Quick', '2.1.0'
  end

  target 'lojinhaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
