using_bundler = defined? Bundler
unless using_bundler
  puts "\nPlease re-run using:".red
  puts "  bundle exec pod install\n\n"
  exit(1)
end

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/inacioferrarini/podspecs'

target 'lojinha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManager'

  #Modules
  # pod 'Common', :path => '../modules/Common'
  pod 'StoreFront', :path => '../modules/StoreFront'
  pod 'Login', :path => '../modules/Login'

  target 'lojinhaTests' do
    inherit! :search_paths
    pod 'Nimble', '8.0.2'
    pod 'Quick', '2.1.0'
    pod 'KIF', :configurations => ['Debug']
    pod 'KIF/IdentifierTests', :configurations => ['Debug']
  end

  target 'lojinhaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
